### ISSUE TITLE
Always generating same image of water on every brushstroke

### ISSUE THREAD

**Issue by MilkManEX** [houseofsecrets/SdPaint#3]
Result of every brush stroke, webui error attached.

![image](https://user-images.githubusercontent.com/16171167/232588854-0c09b903-b869-4dd5-9ef7-51a192af424c.png)

![image](https://user-images.githubusercontent.com/16171167/232588911-2c17e7e8-05c4-461e-8af6-69318e198478.png)

**Comment by ikbentheo** [comment]
Do you have the scribble controlnet?

**Comment by MilkManEX** [comment]
> Do you have the scribble controlnet?

Yeah, as far as I can tell I've got everything as it should be.
![image](https://user-images.githubusercontent.com/16171167/232591281-83e2cb9b-9cd6-4258-902a-bd5b18be0c6d.png)

**Comment by ikbentheo** [comment]
I dont know if that is the right directory. I checked, and that folder is empty in my directory. 

Try putting these files in: 
webui\extensions\sd-webui-controlnet\models

**Comment by MilkManEX** [comment]
Oh I had them there as well. No love.

**Comment by unt-pics** [comment]
> I had that issue because my ControlNet model didnt match the one listed in the payload.json. Once I put the model and hash that I have, it started working.

I have a similar issue. My models have different names, where I can find a hash of them in order to put in payload.json?

<img width="773" alt="image" src="https://user-images.githubusercontent.com/131181237/232835842-a882f87c-a6e8-4045-9047-bb53dc9197bd.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/131181237/232836109-0dd313ee-5436-42b1-bf43-d433ede65439.png">

**Comment by unt-pics** [comment]
Where can I find those hash numbers for other models?
