### ISSUE TITLE
Is there Any Turturios with img2img mode?

### ISSUE THREAD

**Issue by Moeblack** [houseofsecrets/SdPaint#86]
Specifically, what is the difference between this mode and the image-to-image mode in WebUI? 

At first, I thought it was possible to frame an area on the screen and achieve real-time image generation by modifying this area. 

However, it seems that this img2img mode only generates images from the selected picture, and none of the shortcuts can be used.

**Comment by Danamir** [comment]
Yeah, img2img mode was added as an afterthought as a separate mode from the default scribble mode, to use any digital painting as source instead of the SdPaint interface. You only have to save the image and the generation will refresh. It is less polished than the txt2img use, and is not as developed. 

Many recent iterations on LCM real time drawing use a webcam as source, and/or a screen capture device to get the source picture. The main difference beeing that SdPaint img2img only launches a new generation when the image is saved/updated, where the webcam/capture softwares generate continually in the background. 

If you want real time rendering via screen capture, check https://github.com/radames/Real-Time-Latent-Consistency-Model with OBS studio for example.

**Comment by Moeblack** [comment]
thank you, I almost understand.
